version: '3'

networks:
  app-network:
  db-network:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: app.nginx
    ports:
      - "8088:80"
      - "8089:81"
    volumes:
      - ./frontend:/var/www/html/frontend
      - ./backend:/var/www/html/backend
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
      - database
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app.frontend
    volumes:
      - ./frontend:/var/www/html/frontend
    ports:
      - "8080:9000"
    networks:
      - app-network
  
  backend:
    build: ./backend
    container_name: app.backend
    volumes:
      - ./backend:/var/www/html/backend
    ports:
      - "5050:9000"
    networks:
      - app-network
      - db-network
    
  database:
    image: mysql
    container_name: app.database
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - db-network