version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./frontend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

  php:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./frontend:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel