version: '3'

networks:
  app-network:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: app.nginx
    ports:
      - "8088:80"
    volumes:
      - ./frontend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app.frontend
    volumes:
      - ./frontend:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - app-network